#!/usr/bin/env bash
#
# Script to select GTK-server
#
# December 2016 - PvE.
#---------------------------------------------------------------

if [[ $(whoami) != "root" ]]
then
    echo "This script has to be executed as 'root'! Exiting..."
    exit 1
fi

echo
echo "*** Select GTK-server binary and library ***"
echo

BINDIR=/usr/local/bin

SERVER=$(ls ${BINDIR}/gtk-server-* 2>/dev/null)

if [[ -n $SERVER ]]
then
    COUNT=1
    for i in $SERVER
    do
        echo "(${COUNT}) $(basename $i)"
        BIN[$COUNT]=$i
        ((COUNT+=1))
    done
fi
echo

echo -n "Select GTK-server... "
read NR

if [[ $NR -lt 1 || $NR -ge $COUNT ]]
then
    echo "Invalid selection."
    exit 1
fi

ln -sf ${BIN[$NR]} $(dirname ${BIN[$NR]})/gtk-server

#---------------------------------------------------------------

echo

LIBDIR=/usr/local/lib

SERVER=$(ls ${LIBDIR}/libgtk-server-* 2>/dev/null)

if [[ -n $SERVER ]]
then
    COUNT=1
    for i in $SERVER
    do
        echo "(${COUNT}) $(basename $i)"
        LIB[$COUNT]=$i
        ((COUNT+=1))
    done
fi
echo

echo -n "Select GTK-server library... "
read NR

if [[ $NR -lt 1 || $NR -ge $COUNT ]]
then
    echo "Invalid selection."
    exit 1
fi

ln -sf ${LIB[$NR]} $(dirname ${LIB[$NR]})/libgtk-server.so

